### ISSUE TITLE
ERROR with Linux npm package

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoins** [ipsBruno/brute-force-seed-bitcoin#4]
Installing with linux running the command:

npm install blockchain.info/blockexplorer

I run into a error.

**Comment by ipsBruno** [comment]
Paste the error here, please

**Comment by SatoshiNakamotoBitcoins** [comment]
Hello Bruno,

After installing with Linux and installing the npm packages:

npm install bitcoinjs-lib
npm install bip39
npm install blockchain.info

And running node index.js after this...I got this error:

/home/linux/brute-force-seed-bitcoin/node_modules/typeforce/index.js:235
    throw new TfTypeError(surrogate || type, value)
    ^
Error: Expected Buffer, got Promise
    at typeforce (/home/linux/brute-force-seed-bitcoin/node_modules/typeforce/index.js:235:11)
    at Object.fromSeed (/home/linux/brute-force-seed-bitcoin/node_modules/bip32/src/bip32.js:279:5)
    at Timeout._onTimeout (/home/linux/brute-force-seed-bitcoin/index.js:25:43)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

Like to learn from you!

Cheers Satoshi

**Comment by SatoshiNakamotoBitcoins** [comment]
Hello Bruno,

I figured out that line 25 has to be replaced with this line:

xPubKeys[i] = getPubKeyFromRoot(bip32.fromSeed(bip39.mnemonicToSeedSync(xSeedPrv[i] , "")), DerivationPath)

And line 26 added with this:

console.log(xPubKeys[i])

After that it runs fine!

Cheers Satoshi

**Comment by ipsBruno** [comment]
What is your nodejs version?

node -v

**Comment by SatoshiNakamotoBitcoins** [comment]
v8.10.0
But with the adjustments with line 25 and 26 (which I mailed before) it just works fine...
